/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.25).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Court;
import io.swagger.model.ModelApiResponse;
import org.springframework.core.io.Resource;
import io.swagger.model.SportHall;
import io.swagger.model.SportHallRating;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2021-04-08T20:35:21.763Z[GMT]")
@Validated
public interface SportHallApi {

    @Operation(summary = "Create sport hall", description = "", tags={ "sportHall" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "successful operation") })
    @RequestMapping(value = "/sportHall",
        consumes = { "*/*" }, 
        method = RequestMethod.POST)
    ResponseEntity<Void> createSportHall(@Parameter(in = ParameterIn.DEFAULT, description = "Created sportHall object", required=true, schema=@Schema()) @Valid @RequestBody SportHall body);


    @Operation(summary = "Deletes a sport hall", description = "", tags={ "sportHall" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "400", description = "Invalid ID supplied"),
        
        @ApiResponse(responseCode = "404", description = "Sport Hall not found") })
    @RequestMapping(value = "/sportHall/{sportHallId}",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteSportHall(@Parameter(in = ParameterIn.PATH, description = "Sport hall id to delete", required=true, schema=@Schema()) @PathVariable("sportHallId") Long sportHallId);


    @Operation(summary = "Finds sport hall by id", description = "", tags={ "sportHall" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "successful operation", content = @Content(schema = @Schema(implementation = Court.class))),
        
        @ApiResponse(responseCode = "400", description = "Invalid ID supplied"),
        
        @ApiResponse(responseCode = "404", description = "Sport Hall not found") })
    @RequestMapping(value = "/sportHall/{sportHallId}",
        produces = { "application/json", "application/xml" }, 
        method = RequestMethod.GET)
    ResponseEntity<Court> getSportHallById(@Parameter(in = ParameterIn.PATH, description = "Id of sport hall to return", required=true, schema=@Schema()) @PathVariable("sportHallId") Long sportHallId);


    @Operation(summary = "Get sport halls list", description = "", tags={ "sportHall" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "successful operation", content = @Content(array = @ArraySchema(schema = @Schema(implementation = SportHall.class)))) })
    @RequestMapping(value = "/sportHall",
        produces = { "application/json", "application/xml" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<SportHall>> getSportHallsList(@Parameter(in = ParameterIn.QUERY, description = "The maximum number of results to retrieve" ,schema=@Schema()) @Valid @RequestParam(value = "limit", required = false) Integer limit, @Parameter(in = ParameterIn.QUERY, description = "The zero-ary offset into the results" ,schema=@Schema()) @Valid @RequestParam(value = "offset", required = false) Integer offset, @Parameter(in = ParameterIn.QUERY, description = "How to sort the results" ,schema=@Schema(allowableValues={ "id", "name", "location", "rating" }
, defaultValue="id")) @Valid @RequestParam(value = "sort", required = false, defaultValue="id") String sort);


    @Operation(summary = "Rate sport hall", description = "", tags={ "sportHall" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "successful operation", content = @Content(schema = @Schema(implementation = SportHallRating.class))),
        
        @ApiResponse(responseCode = "405", description = "Invalid input") })
    @RequestMapping(value = "/sportHall/{sportHallId}/rate",
        produces = { "application/json", "application/xml" }, 
        consumes = { "application/json", "application/xml" }, 
        method = RequestMethod.POST)
    ResponseEntity<SportHallRating> rateSportHall(@Parameter(in = ParameterIn.PATH, description = "Id of sport hall to rate", required=true, schema=@Schema()) @PathVariable("sportHallId") Long sportHallId, @Parameter(in = ParameterIn.DEFAULT, description = "Rate object that needs to be added", required=true, schema=@Schema()) @Valid @RequestBody SportHallRating body);


    @Operation(summary = "Update an existing sportHall", description = "", tags={ "sportHall" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "400", description = "Invalid ID supplied"),
        
        @ApiResponse(responseCode = "404", description = "SportHall not found"),
        
        @ApiResponse(responseCode = "405", description = "Validation exception") })
    @RequestMapping(value = "/sportHall",
        consumes = { "application/json", "application/xml" }, 
        method = RequestMethod.PUT)
    ResponseEntity<Void> updateSportHall(@Parameter(in = ParameterIn.DEFAULT, description = "Sport Hall object that needs to be updated", required=true, schema=@Schema()) @Valid @RequestBody SportHall body);


    @Operation(summary = "Uploads an image", description = "", tags={ "sportHall" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "successful operation", content = @Content(schema = @Schema(implementation = ModelApiResponse.class))) })
    @RequestMapping(value = "/sportHall/{sportHallId}/uploadImage",
        produces = { "application/json" }, 
        consumes = { "multipart/form-data" }, 
        method = RequestMethod.POST)
    ResponseEntity<ModelApiResponse> uploadSportHallImage(@Parameter(in = ParameterIn.PATH, description = "ID of sport hall to update", required=true, schema=@Schema()) @PathVariable("sportHallId") Long sportHallId, @Parameter(in = ParameterIn.DEFAULT, description = "",schema=@Schema()) @RequestParam(value="additionalMetadata", required=false)  String additionalMetadata, @Parameter(description = "file detail") @Valid @RequestPart("file") MultipartFile file);

}

